import fs from "fs";
import path from "path";

import { getTrackReviewerPacketPublicSummary } from "@/lib/track-reviewer-packets";

export type CuratedDocument = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  audience: string;
  boundary: string;
  docPath: string;
  rawHref: string;
};

const repositoryBlobBase = "https://github.com/X-PACT/PrivateDAO/blob/main";

const hiddenCuratedDocumentSlugs = new Set<string>([
  "superteam-track-submission-matrix-2026",
  "live-submission-review-2026",
  "track-judge-first-openings",
  "track-reviewer-packet-colosseum-frontier",
  "track-reviewer-packet-privacy-track",
  "track-reviewer-packet-rpc-infrastructure",
  "frontier-competition-readiness-2026",
  "competition-track-requirements-2026",
  "competition-execution-playbook",
]);

function isPublicCuratedDocumentSlug(slug: string) {
  return !hiddenCuratedDocumentSlugs.has(slug);
}

export function isIndexableCuratedDocumentSlug(slug: string) {
  return isPublicCuratedDocumentSlug(slug);
}

export function getIndexableCuratedDocuments() {
  return curatedDocuments.filter((document) => isIndexableCuratedDocumentSlug(document.slug));
}

const curatedDocuments: CuratedDocument[] = [
  {
    slug: "agentic-treasury-micropayment-rail",
    title: "Agentic Treasury Micropayment Rail",
    category: "Strategy",
    summary: "Operational brief for DAO-controlled micropayment batches, showing how approved policy becomes batched stablecoin settlement with judge-visible runtime proof and telemetry continuity.",
    audience: "Judges, funders, operators, builders",
    boundary: "Operating brief only; it describes the live rail and Devnet execution target without claiming production stablecoin settlement closure beyond the linked evidence.",
    docPath: "docs/agentic-treasury-micropayment-rail.md",
    rawHref: `${repositoryBlobBase}/docs/agentic-treasury-micropayment-rail.md`,
  },
  {
    slug: "audd-stablecoin-treasury-layer",
    title: "AUDD Stablecoin Treasury Layer",
    category: "Payments",
    summary:
      "Product brief for AUDD merchant settlement, treasury management, invoice collection, programmable Australian-dollar finance, and browser-signed stablecoin billing across the PrivateDAO treasury layer.",
    audience: "Grant reviewers, treasury operators, merchant builders, finance teams, institutional stablecoin partners",
    boundary:
      "Stablecoin operating brief only; it ships route logic, SPL transfer construction, and the official AUDD mint plus funded-wallet activation path.",
    docPath: "docs/audd-stablecoin-treasury-layer.md",
    rawHref: `${repositoryBlobBase}/docs/audd-stablecoin-treasury-layer.md`,
  },
  {
    slug: "pusd-stablecoin-treasury-layer",
    title: "PUSD Stablecoin Treasury Layer",
    category: "Payments",
    summary:
      "Product brief for PUSD confidential payroll, grant distribution, commerce settlement, gaming reward pools, and stablecoin billing proof across the PrivateDAO treasury layer.",
    audience: "Judges, grant reviewers, treasury operators, gaming teams, institutional stablecoin partners",
    boundary:
      "Stablecoin operating brief only; it ships route logic, SPL transfer construction, and the official PUSD mint plus funded-wallet activation path.",
    docPath: "docs/pusd-stablecoin-treasury-layer.md",
    rawHref: `${repositoryBlobBase}/docs/pusd-stablecoin-treasury-layer.md`,
  },
  {
    slug: "zerion-autonomous-agent-policy",
    title: "Zerion Autonomous Agent Policy",
    category: "Agent",
    summary:
      "Policy-bound execution packet for connecting PrivateDAO governance decisions to a Zerion CLI fork with Solana chain lock, spend caps, expiry windows, and approve-before-execute safety.",
    audience: "Judges, agent builders, treasury operators, security reviewers",
    boundary:
      "Agent policy packet only; it documents scoped execution and the route surface without claiming an unrestricted autonomous trading agent.",
    docPath: "docs/zerion-autonomous-agent-policy.md",
    rawHref: `${repositoryBlobBase}/docs/zerion-autonomous-agent-policy.md`,
  },
  {
    slug: "torque-growth-loop",
    title: "Torque Growth Loop",
    category: "Growth",
    summary:
      "Growth-loop packet for turning real PrivateDAO actions into Torque-style custom_events: DAO creation, proposal creation, billing signatures, and learning completion.",
    audience: "Judges, growth teams, ecosystem reviewers, operators",
    boundary:
      "Growth event packet only; static-export surfaces can generate and inspect event payloads while production credentialed forwarding belongs in a server-side relay.",
    docPath: "docs/torque-growth-loop.md",
    rawHref: `${repositoryBlobBase}/docs/torque-growth-loop.md`,
  },
  {
    slug: "final-closure-workplan-2026-04-19",
    title: "Final Closure Workplan 2026",
    category: "Operations",
    summary:
      "Execution checklist for closing PrivateDAO's Testnet runtime, wallet evidence, stablecoin treasury lane, autonomous agent lane, growth loop, Learn module, audit readiness, Android parity, public site, and external submissions.",
    audience: "Operators, reviewers, funders, builders",
    boundary:
      "Operating workplan only; it defines the closure order and validation commands while keeping Mainnet, audit, custody, and sponsor-specific claims tied to evidence.",
    docPath: "docs/final-closure-workplan-2026-04-19.md",
    rawHref: `${repositoryBlobBase}/docs/final-closure-workplan-2026-04-19.md`,
  },
  {
    slug: "ecosystem-capability-map-2026",
    title: "Ecosystem Capability Map 2026",
    category: "Strategy",
    summary:
      "Public map showing how recurring ecosystem requirements were translated into live platform capabilities across private governance, treasury rails, analytics, wallet UX, infrastructure, growth loops, and education.",
    audience: "Reviewers, partners, funders, operators, builders",
    boundary:
      "Capability map only; it explains how ecosystem requirements inform the platform without presenting the site as a list of competition submissions.",
    docPath: "docs/ecosystem-capability-map-2026.md",
    rawHref: `${repositoryBlobBase}/docs/ecosystem-capability-map-2026.md`,
  },
  {
    slug: "track-funding-integration-closure-plan-2026-04-19",
    title: "Track Funding Integration Closure Plan 2026",
    category: "Funding",
    summary:
      "Execution plan for closing PrivateDAO's Testnet gaps while turning every active track into a fundable product corridor with route, packet, proof, and investment-grade narrative.",
    audience: "Founders, funders, judges, operators, submission reviewers",
    boundary:
      "Funding integration plan only; it maps tracks to product lanes and closure evidence without claiming unrecorded sponsor integrations, audit completion, or mainnet real-funds readiness.",
    docPath: "docs/track-funding-integration-closure-plan-2026-04-19.md",
    rawHref: `${repositoryBlobBase}/docs/track-funding-integration-closure-plan-2026-04-19.md`,
  },
  {
    slug: "themiracle-benefit-proposal",
    title: "theMiracle Benefit Proposal",
    category: "Growth",
    summary:
      "Wallet-placement benefit design for theMiracle: targeted DeFi-active Solana governance wallets, one clear PrivateDAO proposal action, $5,000+ perceived incentive value, and conversion analytics tied to wallet-level behavior.",
    audience: "theMiracle reviewers, wallet-growth partners, DAO operators, treasury teams",
    boundary:
      "Submission proposal only; it defines the audience, action, incentive, value, and campaign success criteria without claiming a live theMiracle wallet placement before award selection.",
    docPath: "docs/themiracle-benefit-proposal.md",
    rawHref: `${repositoryBlobBase}/docs/themiracle-benefit-proposal.md`,
  },
  {
    slug: "excellence-closure-matrix-2026-05-06",
    title: "PrivateDAO Excellence Closure Matrix",
    category: "Operations",
    summary:
      "Judge and operator matrix that converts every serious launch gate into a visible product route, evidence schema, verification command, and truth-aligned closure lane.",
    audience: "Judges, operators, investors, security reviewers, ecosystem partners",
    boundary:
      "Closure matrix only; it strengthens the product operating surface without claiming unrecorded custody ceremony, external audit completion, or mainnet real-funds release.",
    docPath: "docs/excellence-closure-matrix-2026-05-06.md",
    rawHref: `${repositoryBlobBase}/docs/excellence-closure-matrix-2026-05-06.md`,
  },
  {
    slug: "aws-namecheap-read-node-cutover-2026-04-29",
    title: "AWS Namecheap Read-Node Cutover",
    category: "Operations",
    summary:
      "Production-style cutover guide for keeping the static frontend on privatedao.org while serving the Testnet read-node from api.privatedao.org with Anchor 1.0.1 program drift checks.",
    audience: "Operators, reviewers, infrastructure partners, security reviewers",
    boundary:
      "Infrastructure runbook only; it defines the live API target, DNS shape, and verification gates without claiming the EC2 host is aligned unless the published remote verifier passes.",
    docPath: "docs/read-node/aws-namecheap-cutover-2026-04-29.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/aws-namecheap-cutover-2026-04-29.md`,
  },
  {
    slug: "encrypted-operations-lane",
    title: "Encrypted Operations Lane",
    category: "Security",
    summary: "Technical brief for the encrypted operations planning surface that helps structure confidential treasury motion, privacy mode, settlement posture, and operator visibility inside the live product.",
    audience: "Operators, reviewers, judges, builders",
    boundary: "Product brief only; it describes the operating surface and how it is used without upgrading confidential settlement claims beyond the linked proof and settlement routes.",
    docPath: "docs/encrypted-operations-lane.md",
    rawHref: `${repositoryBlobBase}/docs/encrypted-operations-lane.md`,
  },
  {
    slug: "jupiter-treasury-route",
    title: "Jupiter Treasury Route",
    category: "Strategy",
    summary: "Product brief for the Jupiter-backed treasury corridor, showing how governed swaps, rebalances, and payout-funding motions are being folded into the same wallet-first operating path.",
    audience: "Judges, buyers, operators, grant reviewers",
    boundary: "Route brief only; it describes the live product direction and next execution milestones without claiming a fully closed Jupiter production integration ahead of the supporting evidence.",
    docPath: "docs/jupiter-treasury-route.md",
    rawHref: `${repositoryBlobBase}/docs/jupiter-treasury-route.md`,
  },
  {
    slug: "devnet-execution-screenshots",
    title: "Devnet Execution Screenshots",
    category: "Reviewer core",
    summary: "Compact visual proof packet with real Solscan captures from the current Devnet execution wallet and the agentic treasury micropayment rail.",
    audience: "Judges, grant reviewers, operators, non-technical visitors",
    boundary: "Screenshots packet only; it visually confirms public Devnet explorer records without replacing the structured rail packet or runtime logs.",
    docPath: "docs/devnet-execution-screenshots.md",
    rawHref: `${repositoryBlobBase}/docs/devnet-execution-screenshots.md`,
  },
  {
    slug: "privacy-and-encryption-proof-guide",
    title: "Privacy And Encryption Proof Guide",
    category: "Reviewer core",
    summary: "Plain-language guide explaining what stays protected, what becomes public, and which real Devnet hashes prove governance secrecy, ZK anchoring, and confidential settlement without turning PrivateDAO into a black box.",
    audience: "Judges, reviewers, non-technical visitors, operators",
    boundary: "Explanation guide only; it links to real Devnet evidence and current proof routes without upgrading unfinished verifier or receipt boundaries.",
    docPath: "docs/privacy-and-encryption-proof-guide.md",
    rawHref: `${repositoryBlobBase}/docs/privacy-and-encryption-proof-guide.md`,
  },
  {
    slug: "selective-disclosure-operating-surface",
    title: "Selective Disclosure Operating Surface",
    category: "Trust",
    summary: "Product-safe explanation of how PrivateDAO opens a narrow reviewer window into private governance and treasury actions without exposing the entire internal workflow.",
    audience: "Judges, operators, partners, auditors",
    boundary: "Operating surface only; it explains the disclosure boundary and live review lanes without claiming finished institutional closure beyond the linked proof routes.",
    docPath: "docs/selective-disclosure-operating-surface.md",
    rawHref: `${repositoryBlobBase}/docs/selective-disclosure-operating-surface.md`,
  },
  {
    slug: "frontend-solana-bootcamp-materials",
    title: "Frontend Solana Bootcamp Materials",
    category: "Education",
    summary: "The complete four-lecture PrivateDAO frontend bootcamp pack: slide-ready materials, starter templates, assignments, quizzes, live routes, and code references for turning a Web2 frontend builder into a Solana dApp operator.",
    audience: "Frontend developers, judges, ecosystem educators, and product builders",
    boundary: "Educational pack only; it teaches the live product and references shipped routes and code without overstating hidden internals or unfinished production gates.",
    docPath: "docs/frontend-solana-bootcamp-materials.md",
    rawHref: `${repositoryBlobBase}/docs/frontend-solana-bootcamp-materials.md`,
  },
  {
    slug: "solana-developer-tooling-proposal-2026",
    title: "Solana Developer Tooling Proposal 2026",
    category: "Strategy",
    summary: "Public-good proposal describing PrivateDAO as live governance infrastructure and developer tooling for reviewer clarity, treasury coordination, and production-intent Solana operations.",
    audience: "Grant reviewers, ecosystem funders, operators, judges",
    boundary: "Proposal surface only; it explains the product, current Devnet posture, and funding direction without claiming that mainnet closure is already complete.",
    docPath: "docs/solana-developer-tooling-proposal-2026.md",
    rawHref: `${repositoryBlobBase}/docs/solana-developer-tooling-proposal-2026.md`,
  },
  {
    slug: "technical-verification-status-2026",
    title: "Technical Progress And Execution Strategy 2026",
    category: "Strategy",
    summary: "Repository-grounded view of what PrivateDAO already ships, what is already evidenced, and which strategic development targets are being actively closed with further support and execution.",
    audience: "Founders, reviewers, funders, operators",
    boundary: "Verification surface only; it keeps roadmap language aligned with repository truth and does not upgrade any operating gate beyond the evidence already linked.",
    docPath: "docs/technical-verification-status-2026.md",
    rawHref: `${repositoryBlobBase}/docs/technical-verification-status-2026.md`,
  },
  {
    slug: "reform-backlog-index-2026",
    title: "Reform Backlog Index 2026",
    category: "Strategy",
    summary: "Canonical in-repo index for the PrivateDAO reform program, routing execution across protocol, runtime and infrastructure, product UX, and funding workstreams.",
    audience: "Founders, operators, reviewers, funders",
    boundary: "Execution index only; it organizes work but does not claim that any listed gate or tranche is already complete.",
    docPath: "docs/reform-backlog-index-2026.md",
    rawHref: `${repositoryBlobBase}/docs/reform-backlog-index-2026.md`,
  },
  {
    slug: "reform-backlog-protocol-2026",
    title: "Protocol Reform Backlog 2026",
    category: "Strategy",
    summary: "Backlog for Solana program modularity, error centralization, account validation, migration discipline, and audit-readiness work.",
    audience: "Protocol engineers, reviewers, operators",
    boundary: "Backlog only; it sets protocol priorities without claiming the program refactor or audit closure is already complete.",
    docPath: "docs/reform-backlog-protocol-2026.md",
    rawHref: `${repositoryBlobBase}/docs/reform-backlog-protocol-2026.md`,
  },
  {
    slug: "reform-backlog-runtime-infra-2026",
    title: "Runtime And Infrastructure Backlog 2026",
    category: "Infrastructure",
    summary: "Backlog for wallet runtime evidence, monitoring delivery, settlement receipts, read-node maturity, and production operations uplift.",
    audience: "Operators, infrastructure reviewers, funders",
    boundary: "Backlog only; it does not claim monitoring delivery, real-device coverage, or settlement evidence is already fully closed.",
    docPath: "docs/reform-backlog-runtime-infra-2026.md",
    rawHref: `${repositoryBlobBase}/docs/reform-backlog-runtime-infra-2026.md`,
  },
  {
    slug: "rpcfast-hackathon-infrastructure-plan",
    title: "RPCFast Hackathon Infrastructure Plan",
    category: "Infrastructure",
    summary: "Operating plan for RPCFast Hackathon/Aperture support, Devnet Yellowstone gRPC, Testnet release-candidate rehearsal, and mainnet data-plane readiness.",
    audience: "Infrastructure reviewers, operators, funders, judges",
    boundary: "Infrastructure activation plan only; it records supported RPC/gRPC capability and rollout stages without exposing API keys or claiming mainnet custody closure.",
    docPath: "docs/rpcfast-hackathon-infrastructure-plan.md",
    rawHref: `${repositoryBlobBase}/docs/rpcfast-hackathon-infrastructure-plan.md`,
  },
  {
    slug: "anchor-1-migration-evidence-2026-04-30",
    title: "Anchor 1 Migration Evidence",
    category: "Infrastructure",
    summary:
      "Current Testnet evidence for the Anchor 1.0.1 migration, upgraded program ID, deploy signature, ProgramData account, web and Android constants, and remaining hardening notes.",
    audience: "Judges, infrastructure reviewers, operators, investors",
    boundary:
      "Anchor 1 Testnet deployment evidence only; it does not claim production mainnet custody, external audit completion, or real-funds release.",
    docPath: "docs/anchor-1-migration-evidence-2026-04-30.md",
    rawHref: `${repositoryBlobBase}/docs/anchor-1-migration-evidence-2026-04-30.md`,
  },
  {
    slug: "testnet-migration-report-2026-04-18",
    title: "Testnet Migration Report",
    category: "Infrastructure",
    summary: "Historical Testnet migration packet for the pre-Anchor-1 deployment, lifecycle rehearsal, and remaining release boundaries.",
    audience: "Infrastructure reviewers, operators, funders, judges",
    boundary: "Testnet standard governance and SOL treasury lifecycle proof only; it does not claim custody transfer, confidential settlement closure, audit completion, or mainnet readiness.",
    docPath: "docs/testnet-migration-report-2026-04-18.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-migration-report-2026-04-18.md`,
  },
  {
    slug: "testnet-architecture-migration-2026-04-19",
    title: "Testnet Architecture Migration",
    category: "Infrastructure",
    summary: "Operating packet for the full public shift from Devnet rehearsal history into the current Solana Testnet architecture, including RPC defaults, wallet routing, UI language, and proof references.",
    audience: "Infrastructure reviewers, operators, funders, judges",
    boundary: "Testnet operating boundary only; it preserves Devnet as transition evidence and keeps Mainnet gated on audit, custody, monitoring, and cutover closure.",
    docPath: "docs/testnet-architecture-migration-2026-04-19.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-architecture-migration-2026-04-19.md`,
  },
  {
    slug: "testnet-lifecycle-rehearsal-2026-05-06",
    title: "Testnet Lifecycle Rehearsal 2026-05-06",
    category: "Infrastructure",
    summary:
      "Fresh Solana Testnet proof for DAO creation, proposal creation, treasury deposit, commit, reveal, finalize, execute, Supabase receipt intake, and treasury delta verification.",
    audience: "Judges, infrastructure reviewers, operators, funders",
    boundary:
      "Standard Testnet governance and SOL treasury execution proof only; custody/multisig and full Umbra claim proof remain separate gated evidence lanes.",
    docPath: "docs/testnet-lifecycle-rehearsal-2026-05-06.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-lifecycle-rehearsal-2026-05-06.md`,
  },
  {
    slug: "testnet-lifecycle-rehearsal-2026-05-07",
    title: "Testnet Lifecycle Rehearsal 2026-05-07",
    category: "Infrastructure",
    summary:
      "Latest Solana Testnet proof for DAO creation, proposal creation, treasury deposit, commit, reveal, finalize, execute, Supabase receipt intake, and treasury delta verification against the Anchor 1.0.1 program.",
    audience: "Judges, infrastructure reviewers, operators, funders",
    boundary:
      "Standard Testnet governance and SOL treasury execution proof only; custody/multisig and full Umbra claim proof remain separate gated evidence lanes.",
    docPath: "docs/testnet-lifecycle-rehearsal-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-lifecycle-rehearsal-2026-05-07.md`,
  },
  {
    slug: "testnet-lifecycle-rehearsal-2026-04-19",
    title: "Testnet Lifecycle Rehearsal",
    category: "Infrastructure",
    summary: "Explorer-linked Testnet proof for DAO creation, proposal creation, treasury deposit, commit, reveal, finalize, execute, and treasury delta verification.",
    audience: "Infrastructure reviewers, operators, funders, judges",
    boundary: "Standard governance and SOL treasury execution proof only; browser-wallet captures, custody/multisig, and confidential payout settlement receipts remain separate packets.",
    docPath: "docs/testnet-lifecycle-rehearsal-2026-04-19.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-lifecycle-rehearsal-2026-04-19.md`,
  },
  {
    slug: "reform-backlog-product-ux-2026",
    title: "Product UX Reform Backlog 2026",
    category: "Strategy",
    summary: "Backlog for wallet-first governance flow quality, guided-route clarity, Arabic and RTL support, mobile execution, and ecosystem integration surfaces.",
    audience: "Product leads, frontend engineers, operators",
    boundary: "Backlog only; it does not claim the full operator journey or Arabic product layer is already finished.",
    docPath: "docs/reform-backlog-product-ux-2026.md",
    rawHref: `${repositoryBlobBase}/docs/reform-backlog-product-ux-2026.md`,
  },
  {
    slug: "reform-backlog-funding-2026",
    title: "Funding And Submission Backlog 2026",
    category: "Strategy",
    summary: "Backlog for truth-aligned grants, external reviews, pricing posture, partner-facing claims, and commercial fundability.",
    audience: "Founders, operators, grant reviewers, funders",
    boundary: "Backlog only; it improves funding posture but does not itself make any grant ask approved or any pricing model production-final.",
    docPath: "docs/reform-backlog-funding-2026.md",
    rawHref: `${repositoryBlobBase}/docs/reform-backlog-funding-2026.md`,
  },
  {
    slug: "engineering-delivery-model",
    title: "Engineering Delivery Model",
    category: "Operations",
    summary: "Shared engineering operating model for how PrivateDAO is designed, reviewed, shipped, and explained as one coordinated product team across governance, payments, proof, infrastructure, and education.",
    audience: "Community members, contributors, reviewers, operators",
    boundary: "Operating model only; it explains how the work is organized and reviewed without claiming additional product closure beyond the linked proof and delivery surfaces.",
    docPath: "docs/engineering-delivery-model.md",
    rawHref: `${repositoryBlobBase}/docs/engineering-delivery-model.md`,
  },
  {
    slug: "superteam-track-submission-matrix-2026",
    title: "Product Alignment Matrix 2026",
    category: "Strategy",
    summary: "Public alignment matrix for the product lanes that support PrivateDAO without exposing sponsor-by-sponsor tactics.",
    audience: "Founders, operators, grant reviewers, judges",
    boundary: "Public product-alignment guidance only; it keeps the focus on product lanes, packets, and truth boundaries without documenting private submission tactics.",
    docPath: "docs/superteam-track-submission-matrix-2026.md",
    rawHref: `${repositoryBlobBase}/docs/superteam-track-submission-matrix-2026.md`,
  },
  {
    slug: "live-submission-review-2026",
    title: "Product Progress Note 2026",
    category: "Strategy",
    summary: "Public progress note showing which product lanes are being strengthened in the live build.",
    audience: "Founders, operators, judges, grant reviewers",
    boundary: "Public progress note only; it describes product work in motion and does not expose sponsor-by-sponsor submission handling.",
    docPath: "docs/live-submission-review-2026.md",
    rawHref: `${repositoryBlobBase}/docs/live-submission-review-2026.md`,
  },
  {
    slug: "browser-wallet-runtime",
    title: "Browser-Wallet Runtime Evidence",
    category: "Reviewer core",
    summary: "Generated intake packet for browser-wallet runtime captures across Phantom, Solflare, Backpack, and Glow in the live web governance lane.",
    audience: "Judges, reviewers, operators",
    boundary: "Capture registry only; it does not claim browser-wallet runtime proof exists until actual injected-wallet runs are recorded.",
    docPath: "docs/runtime/browser-wallet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/runtime/browser-wallet.generated.md`,
  },
  {
    slug: "token-architecture",
    title: "Token Architecture",
    category: "Strategy",
    summary: "Canonical explanation of what the PrivateDAO token does now, what it gates, and how it stays aligned with governance rather than speculative tokenomics.",
    audience: "Judges, buyers, grant reviewers, operators",
    boundary: "Architecture note only; it does not claim a mainnet market token launch or expand token utility beyond the live documented Devnet governance surface.",
    docPath: "docs/token.md",
    rawHref: `${repositoryBlobBase}/docs/token.md`,
  },
  {
    slug: "pdao-token-surface",
    title: "PDAO Token Surface",
    category: "Reviewer core",
    summary: "Reviewer-safe token surface for preserved PDAO governance-token evidence, including mint details, attested transactions, disabled mint authority, and product-facing interpretation.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Preserved Devnet token evidence only; it does not claim a public mainnet token launch or speculative market posture.",
    docPath: "docs/pdao-token.md",
    rawHref: `${repositoryBlobBase}/docs/pdao-token.md`,
  },
  {
    slug: "payments-reviewer-fast-path",
    title: "Payments Reviewer Fast Path",
    category: "Reviewer core",
    summary: "Shortest reviewer-visible path into treasury reviewer packet, canonical custody proof, services payments rail, and command-center payout route.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Fast-path only; it does not upgrade custody, authority-transfer, or mainnet treasury claims beyond the underlying truth surfaces.",
    docPath: "docs/payments-reviewer-fast-path.md",
    rawHref: `${repositoryBlobBase}/docs/payments-reviewer-fast-path.md`,
  },
  {
    slug: "reviewer-fast-path",
    title: "Reviewer Fast Path",
    category: "Reviewer core",
    summary: "Shortest reviewer path across live proof, V3 hardening, trust links, and launch boundary surfaces.",
    audience: "Judges, auditors, technical reviewers",
    boundary: "Curated in-app view only. The canonical query-driven docs viewer remains in docs/ until full parity exists.",
    docPath: "docs/reviewer-fast-path.md",
    rawHref: `${repositoryBlobBase}/docs/reviewer-fast-path.md`,
  },
  {
    slug: "grand-champion-technical-review-2026-05-22",
    title: "Grand Champion Technical Review",
    category: "Reviewer core",
    summary: "Judging-stage technical review covering wallet execution boundaries, visitor transaction counters, compliance UX clarity, treasury handoff stability, and the founder-built business narrative.",
    audience: "Judges, technical reviewers, grant reviewers, operators",
    boundary: "Technical review and judging narrative; it documents live Devnet evidence and production gates without claiming completed mainnet release.",
    docPath: "docs/grand-champion-technical-review-2026-05-22.md",
    rawHref: `${repositoryBlobBase}/docs/grand-champion-technical-review-2026-05-22.md`,
  },
  {
    slug: "frontier-adjacent-project-completion-map-2026-05-22",
    title: "Frontier Adjacent Project Completion Map 2026-05-22",
    category: "Reviewer core",
    summary:
      "Strategic completion map for large adjacent Web3 product types, showing how PrivateDAO completes AI, payments, wallets, governance, privacy, infrastructure, Android, proof, and business routing as one operating layer.",
    audience: "Judges, reviewers, funders, operators",
    boundary:
      "Strategic completion map only; it describes product-category completion priorities without naming external projects.",
    docPath: "docs/frontier-adjacent-project-completion-map-2026-05-22.md",
    rawHref: `${repositoryBlobBase}/docs/frontier-adjacent-project-completion-map-2026-05-22.md`,
  },
  {
    slug: "grand-champion-10-level-improvement-map-2026-05-22",
    title: "Grand Champion 10-Level Improvement Map",
    category: "Reviewer core",
    summary:
      "Ten-level execution map for strengthening PrivateDAO across first-minute UX, wallet execution, Android parity, proof continuity, confidential operations, intelligence, business conversion, security, repository reviewability, and judging narrative.",
    audience: "Judges, reviewers, operators, buyers, technical diligence teams",
    boundary:
      "Execution map only; it defines improvement standards and review paths without claiming external audit completion or mainnet real-funds readiness.",
    docPath: "docs/grand-champion-10-level-improvement-map-2026-05-22.md",
    rawHref: `${repositoryBlobBase}/docs/grand-champion-10-level-improvement-map-2026-05-22.md`,
  },
  {
    slug: "provider-to-encrypted-execution-spine-2026-05-22",
    title: "Provider To Encrypted Execution Spine",
    category: "Architecture",
    summary:
      "Architecture brief for the GoldRush decision-intelligence corridor that connects provider data, QVAC analysis, REFHE / Encrypt / IKA preparation, wallet-first execution, and proof continuity.",
    audience: "Judges, operators, reviewers, builders",
    boundary:
      "Architecture brief only; it documents the product spine and Testnet routing without claiming Mainnet custody closure, external audit completion, or unrestricted autonomous execution.",
    docPath: "docs/provider-to-encrypted-execution-spine-2026-05-22.md",
    rawHref: `${repositoryBlobBase}/docs/provider-to-encrypted-execution-spine-2026-05-22.md`,
  },
  {
    slug: "reviewer-fast-path-2026-05-06",
    title: "Reviewer Fast Path 2026-05-06",
    category: "Reviewer core",
    summary: "Current judge-first route map for Anchor 1.0.1, QVAC local inference, Umbra relayer readiness, Supabase timeline behavior, AWS read-node paths, and mainnet truth boundary.",
    audience: "Judges, auditors, infrastructure reviewers, operators",
    boundary: "Current fast-path only; it records live Testnet and hosted-read truth without claiming completed mainnet custody ceremony.",
    docPath: "docs/reviewer-fast-path-2026-05-06.md",
    rawHref: `${repositoryBlobBase}/docs/reviewer-fast-path-2026-05-06.md`,
  },
  {
    slug: "umbra-devnet-relayer-receipt-2026-05-06",
    title: "Umbra Devnet Relayer Receipt",
    category: "Reviewer core",
    summary: "Hosted AWS read-node evidence for Umbra Devnet relayer health, relayer info, supported mints, and a private settlement intent receipt.",
    audience: "Judges, privacy reviewers, infrastructure reviewers, operators",
    boundary: "Relayer readiness and receipt evidence only; full Umbra claim submission still requires SDK-generated ZK proof data and UTXO slot data.",
    docPath: "docs/umbra-devnet-relayer-receipt-2026-05-06.md",
    rawHref: `${repositoryBlobBase}/docs/umbra-devnet-relayer-receipt-2026-05-06.md`,
  },
  {
    slug: "testnet-integration-runtime-closure-2026-05-07",
    title: "Testnet Integration Runtime Closure 2026-05-07",
    category: "Reviewer core",
    summary:
      "Fresh Solana Testnet lifecycle proof plus live AWS read-node checks for Covalent GoldRush, Zerion, Umbra relayer, MagicBlock, QVAC, and private-settlement receipt paths.",
    audience: "Judges, privacy reviewers, infrastructure reviewers, operators",
    boundary:
      "Fresh runtime packet only. It distinguishes real Testnet execution from vendor intent receipts and does not claim full Umbra claim execution, Cloak relay execution, or on-chain ZK verifier CPI where those are still separate integration boundaries.",
    docPath: "docs/testnet-integration-runtime-closure-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-integration-runtime-closure-2026-05-07.md`,
  },
  {
    slug: "testnet-refhe-encrypt-ika-commitment-2026-05-07",
    title: "Testnet REFHE Encrypt/IKA Commitment 2026-05-07",
    category: "Reviewer core",
    summary:
      "Fresh Solana Testnet REFHE evidence path: confidential payout proposal, payout plan, REFHE envelope configuration, settlement, and verifier-program binding.",
    audience: "Judges, Encrypt/IKA reviewers, privacy reviewers, operators",
    boundary:
      "Real Testnet commitment and settlement evidence for proposal-bound confidential execution metadata. It does not claim external FHE computation-service custody.",
    docPath: "docs/testnet-refhe-encrypt-ika-commitment-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-refhe-encrypt-ika-commitment-2026-05-07.md`,
  },
  {
    slug: "testnet-zk-verification-receipts-2026-05-07",
    title: "Testnet ZK Verification Receipts 2026-05-07",
    category: "Reviewer core",
    summary:
      "Fresh Solana Testnet ZK proof anchors and parallel verification receipts for vote, delegation, and tally layers on the current confidential proposal.",
    audience: "Judges, ZK reviewers, privacy reviewers, operators",
    boundary:
      "Real Testnet proof-continuity evidence. It records anchors and verification receipts; verifier-CPI enforcement remains the stricter production mode.",
    docPath: "docs/testnet-zk-verification-receipts-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/testnet-zk-verification-receipts-2026-05-07.md`,
  },
  {
    slug: "solrouter-encrypted-ai-evidence-2026-05-07",
    title: "SolRouter Encrypted AI Evidence 2026-05-07",
    category: "Reviewer core",
    summary:
      "Local encrypted AI-output evidence for the SolRouter lane, including deterministic operation brief generation, AES-GCM encryption, and plaintext/ciphertext hashes.",
    audience: "Judges, AI reviewers, privacy reviewers, operators",
    boundary:
      "Local encrypted-output proof only. It proves the product can encrypt AI briefs before they leave the device, without claiming SolRouter vendor custody or external relay execution.",
    docPath: "docs/solrouter-encrypted-ai-evidence-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/solrouter-encrypted-ai-evidence-2026-05-07.md`,
  },
  {
    slug: "umbra-intent-evidence-2026-05-07",
    title: "Umbra Intent Evidence 2026-05-07",
    category: "Reviewer core",
    summary:
      "Reviewer packet for the PrivateDAO Umbra lane: stealth-settlement intent, recipient privacy hash, relayer readiness, and the exact SDK/UTXO claim boundary.",
    audience: "Judges, Umbra reviewers, privacy reviewers, operators",
    boundary:
      "Intent and relayer-readiness evidence only. It does not claim a full Umbra UTXO claim without SDK-generated proof_account_data and UTXO slot data.",
    docPath: "docs/umbra-intent-evidence-2026-05-07.md",
    rawHref: `${repositoryBlobBase}/docs/umbra-intent-evidence-2026-05-07.md`,
  },
  {
    slug: "solrouter-vs-qvac-boundary",
    title: "SolRouter vs QVAC Boundary",
    category: "AI",
    summary:
      "Clear product boundary between QVAC local-first sensitive-decision inference and SolRouter encrypted general-analysis output handling.",
    audience: "Judges, AI reviewers, privacy reviewers, operators",
    boundary:
      "Boundary explainer only. It separates local inference from encrypted AI-output routing without claiming SolRouter replaces QVAC.",
    docPath: "docs/solrouter-vs-qvac-boundary.md",
    rawHref: `${repositoryBlobBase}/docs/solrouter-vs-qvac-boundary.md`,
  },
  {
    slug: "treasury-reviewer-packet",
    title: "Treasury Reviewer Packet",
    category: "Reviewer core",
    summary: "Generated treasury-facing reviewer packet with strict sender discipline, reference-linked rails, payments fit, reviewer truth links, and exact gate visibility.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Reviewer packet only; it does not claim completed custody ceremony or real-funds production readiness.",
    docPath: "docs/treasury-reviewer-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/treasury-reviewer-packet.generated.md`,
  },
  {
    slug: "reviewer-telemetry-packet",
    title: "Reviewer Telemetry Packet",
    category: "Reviewer core",
    summary: "Generated reviewer-visible route into telemetry, hosted reads, runtime evidence, indexed governance, and the infrastructure value layer behind PrivateDAO.",
    audience: "Judges, infrastructure reviewers, grant reviewers, operators",
    boundary: "Generated telemetry packet only; it does not claim external analytics partnerships or production mainnet readiness.",
    docPath: "docs/reviewer-telemetry-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/reviewer-telemetry-packet.generated.md`,
  },
  {
    slug: "read-node-snapshot",
    title: "Read-Node Snapshot",
    category: "Infrastructure",
    summary: "Generated read-node snapshot with indexed proposal counts, runtime path, confidential payout coverage, featured proposal contexts, and current Devnet load profiles.",
    audience: "Judges, infrastructure reviewers, operators, buyers",
    boundary: "Snapshot only; it reflects the indexed Devnet state and does not by itself claim same-domain hosted-read deployment is already live in production.",
    docPath: "docs/read-node/snapshot.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/snapshot.generated.md`,
  },
  {
    slug: "read-node-ops",
    title: "Read-Node Ops Snapshot",
    category: "Infrastructure",
    summary: "Operator-facing read-node overview covering backend coverage, supported Devnet profiles, health endpoints, metrics path, and same-domain deployment target.",
    audience: "Operators, infrastructure reviewers, judges",
    boundary: "Ops packet only; it documents the current backend-indexer posture and deployment target without claiming same-domain reverse proxy closure on the live static site.",
    docPath: "docs/read-node/ops.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/ops.generated.md`,
  },
  {
    slug: "read-node-indexer",
    title: "Read Node And Indexer",
    category: "Infrastructure",
    summary: "Canonical backend read-path brief covering pooled reads, cached runtime inspection, proposal lookup, wallet readiness checks, and the read-only service boundary.",
    audience: "Operators, infrastructure reviewers, judges, buyers",
    boundary: "Architecture and service-boundary packet only; it does not claim same-domain deployment is already live on the current static site.",
    docPath: "docs/read-node/indexer.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/indexer.md`,
  },
  {
    slug: "read-node-same-domain-deploy",
    title: "Read-Node Same-Domain Deploy",
    category: "Infrastructure",
    summary: "Deployment target for serving the static frontend and the read node behind one origin so `/api/v1` becomes a real product rail instead of a documentation-only target.",
    audience: "Operators, infra leads, reviewers",
    boundary: "Deployment target only; the current live site remains static until a separate backend host and reverse proxy are actually cut over.",
    docPath: "docs/read-node/same-domain-deploy.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/same-domain-deploy.md`,
  },
  {
    slug: "read-node-backend-cutover",
    title: "Read-Node Backend Cutover Packet",
    category: "Infrastructure",
    summary: "Generated cutover packet for moving read-node from reviewer-visible evidence into a real hosted backend corridor, with deployment target, public proof, route binding, and UI fallback policy.",
    audience: "Operators, infrastructure reviewers, judges, buyers",
    boundary: "Cutover packet only; it does not claim that same-domain `/api/v1` is already live on the current public static site.",
    docPath: "docs/read-node/backend-cutover-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/backend-cutover-packet.generated.md`,
  },
  {
    slug: "audit-packet",
    title: "Audit Packet",
    category: "Reviewer core",
    summary: "Generated packet that ties audit-facing evidence, V3 surfaces, and launch materials together.",
    audience: "Judges, auditors, security reviewers",
    boundary: "Rendered in-app as a reviewer-friendly subset. Raw markdown remains the authoritative file.",
    docPath: "docs/audit-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/audit-packet.generated.md`,
  },
  {
    slug: "gpt-5-5-agent-security-review-ar",
    title: "مراجعة أمنية بفريق وكلاء GPT-5.5",
    category: "Security",
    summary: "AI-assisted security review covering the PrivateDAO web app and Android app, with validated findings, release gates, and Testnet boundary decisions.",
    audience: "Judges, security reviewers, operators, Android reviewers",
    boundary: "Internal GPT-5.5 agent-team review only; it does not replace external audit, custody sign-off, or mainnet production certification.",
    docPath: "docs/gpt-5-5-agent-security-review-ar.md",
    rawHref: `${repositoryBlobBase}/docs/gpt-5-5-agent-security-review-ar.md`,
  },
  {
    slug: "live-proof-v3",
    title: "Live Proof V3",
    category: "Reviewer core",
    summary: "Dedicated additive hardening proof for Governance V3 and Settlement V3 on Devnet.",
    audience: "Judges, reviewers, protocol operators",
    boundary: "Devnet proof only; not a mainnet custody claim.",
    docPath: "docs/test-wallet-live-proof-v3.generated.md",
    rawHref: `${repositoryBlobBase}/docs/test-wallet-live-proof-v3.generated.md`,
  },
  {
    slug: "governance-hardening-v3",
    title: "Governance Hardening V3",
    category: "Security",
    summary: "Token-supply quorum snapshots, rebate vault isolation, and additive governance policy hardening.",
    audience: "Security reviewers, operators, protocol readers",
    boundary: "Versioned additive hardening; legacy protocol path remains intact.",
    docPath: "docs/governance-hardening-v3.md",
    rawHref: `${repositoryBlobBase}/docs/governance-hardening-v3.md`,
  },
  {
    slug: "zk-capability-matrix",
    title: "ZK Capability Matrix",
    category: "Security",
    summary: "PrivateDAO-specific matrix for what the ZK layer proves today, how it is verified, and what remains explicitly out of scope.",
    audience: "Judges, security reviewers, operators",
    boundary: "Truth-aligned matrix only; it does not upgrade the repo beyond the actual verifier and launch boundaries.",
    docPath: "docs/zk-capability-matrix.md",
    rawHref: `${repositoryBlobBase}/docs/zk-capability-matrix.md`,
  },
  {
    slug: "canonical-verifier-boundary-decision",
    title: "Canonical Verifier Boundary Decision",
    category: "Security",
    summary: "Decision surface for whether the long-term privacy boundary remains receipt-based or moves to a stricter verifier-program boundary.",
    audience: "Judges, security reviewers, operators, funders",
    boundary: "Decision packet only; it does not claim the stronger verifier-program path is already complete or production-frozen.",
    docPath: "docs/canonical-verifier-boundary-decision.md",
    rawHref: `${repositoryBlobBase}/docs/canonical-verifier-boundary-decision.md`,
  },
  {
    slug: "cryptographic-confidence-engine",
    title: "Cryptographic Confidence Engine",
    category: "Security",
    summary: "Deterministic scoring model for how ZK, REFHE, MagicBlock, Fast RPC, and hardening surfaces change the confidence profile of each proposal pattern.",
    audience: "Judges, security reviewers, operators, buyers",
    boundary: "Interpretation layer only; it does not replace audit, custody, or formal security proofs.",
    docPath: "docs/cryptographic-confidence-engine.md",
    rawHref: `${repositoryBlobBase}/docs/cryptographic-confidence-engine.md`,
  },
  {
    slug: "settlement-hardening-v3",
    title: "Settlement Hardening V3",
    category: "Security",
    summary: "Proposal-scoped settlement policy snapshots, evidence aging, payout caps, and single-use settlement consumption.",
    audience: "Security reviewers, operators, protocol readers",
    boundary: "Curated surface only; confidential payout semantics still depend on the underlying docs and program path.",
    docPath: "docs/settlement-hardening-v3.md",
    rawHref: `${repositoryBlobBase}/docs/settlement-hardening-v3.md`,
  },
  {
    slug: "launch-trust-packet",
    title: "Launch Trust Packet",
    category: "Trust",
    summary: "Custody, audit, pilot, and runtime boundaries tied into one buyer- and reviewer-readable packet.",
    audience: "Buyers, judges, operators",
    boundary: "Keeps release-path work explicit rather than implying completed production readiness.",
    docPath: "docs/launch-trust-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/launch-trust-packet.generated.md`,
  },
  {
    slug: "mainnet-blockers",
    title: "Mainnet Blockers",
    category: "Trust",
    summary: "Canonical list of custody, audit, runtime, and release gates before real-funds cutover.",
    audience: "Operators, buyers, reviewers",
    boundary: "This is a release-gate surface, not a launch approval.",
    docPath: "docs/mainnet-blockers.md",
    rawHref: `${repositoryBlobBase}/docs/mainnet-blockers.md`,
  },
  {
    slug: "mainnet-external-closure-packet",
    title: "Mainnet External Closure Packet",
    category: "Trust",
    summary: "Single operator packet for the remaining external-only path: PDAO metadata cutover, custody and authority closure, deploy-only SOL funding, and the exact point at which mainnet can truthfully be called funding-ready.",
    audience: "Operators, buyers, reviewers, release owners",
    boundary: "Closure packet only; it does not claim that external signers, update authority, or cutover ceremony have already executed.",
    docPath: "docs/mainnet-external-closure-packet.md",
    rawHref: `${repositoryBlobBase}/docs/mainnet-external-closure-packet.md`,
  },
  {
    slug: "devnet-rehearsal-multisig",
    title: "Devnet Rehearsal Multisig",
    category: "Trust",
    summary: "Live Devnet rehearsal multisig packet recording the created 2-of-3 signer set, multisig address, and creation signature without overstating it as the production custody closure.",
    audience: "Operators, reviewers, judges",
    boundary: "Rehearsal artifact only; it does not replace the production multisig, mainnet authority transfer, or release ceremony closure.",
    docPath: "docs/devnet-rehearsal-multisig.md",
    rawHref: `${repositoryBlobBase}/docs/devnet-rehearsal-multisig.md`,
  },
  {
    slug: "production-style-custody-closure-plan",
    title: "Production-Style Custody Closure Plan",
    category: "Trust",
    summary: "Minimal-delta plan for moving from the live Devnet rehearsal multisig to a production-shaped custody closure model without overstating that rehearsal artifacts are already production custody.",
    audience: "Operators, reviewers, release owners",
    boundary: "Planning packet only; it does not claim the production multisig, timelock, or authority transfers already exist.",
    docPath: "docs/production-style-custody-closure-plan.md",
    rawHref: `${repositoryBlobBase}/docs/production-style-custody-closure-plan.md`,
  },
  {
    slug: "production-mainnet-closure-checklist",
    title: "Production Mainnet Closure Checklist",
    category: "Trust",
    summary: "Exact split between what is already closed internally and what still remains external before any stronger production claim can be made.",
    audience: "Operators, reviewers, release owners",
    boundary: "Closure checklist only; it does not claim that production multisig, timelock, or authority transfers are already complete.",
    docPath: "docs/production-mainnet-closure-checklist.md",
    rawHref: `${repositoryBlobBase}/docs/production-mainnet-closure-checklist.md`,
  },
  {
    slug: "brand-search-ops",
    title: "Brand Search Ops",
    category: "Growth",
    summary: "Exact operational checklist for turning on-site SEO work into real brand-search visibility for `PrivateDAO` and its Arabic variants through canonical indexing and search-console submission.",
    audience: "Operators, growth owners, reviewers",
    boundary: "Search operations packet only; it improves crawl and index readiness but does not guarantee first-position ranking by itself.",
    docPath: "docs/brand-search-ops.md",
    rawHref: `${repositoryBlobBase}/docs/brand-search-ops.md`,
  },
  {
    slug: "ownership-and-contact",
    title: "Operating Contact Surface",
    category: "Trust",
    summary: "Public operating contact surface for investment, partnerships, pilots, and operator coordination around the live PrivateDAO product and its release path.",
    audience: "Investors, donors, partners, reviewers, operators",
    boundary: "Contact packet only; it does not alter custody, authority-transfer, or legal structure beyond the practical coordination information recorded in the document.",
    docPath: "docs/ownership-and-contact.md",
    rawHref: `${repositoryBlobBase}/docs/ownership-and-contact.md`,
  },
  {
    slug: "trust-package",
    title: "Trust Package",
    category: "Trust",
    summary: "Buyer-readable trust and proof narrative that connects product surfaces to security and launch truth.",
    audience: "Buyers, operators, reviewers",
    boundary: "Commercial trust framing remains tied to the underlying proof and operating-gate docs.",
    docPath: "docs/trust-package.md",
    rawHref: `${repositoryBlobBase}/docs/trust-package.md`,
  },
  {
    slug: "pilot-program",
    title: "Pilot Program",
    category: "Commercial",
    summary: "Week-by-week pilot structure that frames onboarding, trust packets, and execution readiness for early adopters.",
    audience: "Buyers, operators, pilot teams",
    boundary: "Commercial rollout framing only; it does not turn active release work into shipped infrastructure.",
    docPath: "docs/pilot-program.md",
    rawHref: `${repositoryBlobBase}/docs/pilot-program.md`,
  },
  {
    slug: "service-level-agreement",
    title: "Service Level Agreement",
    category: "Commercial",
    summary: "Hosted ops and service-boundary framing for response expectations, support surfaces, and operator responsibilities.",
    audience: "Buyers, operators, procurement",
    boundary: "Service framing depends on the underlying proof and runtime surfaces; it is not a live enterprise SLA claim by itself.",
    docPath: "docs/service-level-agreement.md",
    rawHref: `${repositoryBlobBase}/docs/service-level-agreement.md`,
  },
  {
    slug: "pricing-model",
    title: "Pricing Model",
    category: "Commercial",
    summary: "Packaging for pilot, API, confidential governance support, and longer-term operating engagements.",
    audience: "Buyers, operators, procurement",
    boundary: "Commercial packaging remains informational until paired with an actual engagement.",
    docPath: "docs/pricing-model.md",
    rawHref: `${repositoryBlobBase}/docs/pricing-model.md`,
  },
  {
    slug: "service-catalog",
    title: "Service Catalog",
    category: "Commercial",
    summary: "Buyer-facing inventory of hosted read API, ops assistance, and confidential governance support services.",
    audience: "Buyers, operators, partnerships",
    boundary: "Service catalog is a product surface, not a claim that every package is currently live-operated.",
    docPath: "docs/service-catalog.md",
    rawHref: `${repositoryBlobBase}/docs/service-catalog.md`,
  },
  {
    slug: "production-custody-ceremony",
    title: "Production Custody Ceremony",
    category: "Operations",
    summary: "Operational handoff for multisig creation, authority transfer, and custody evidence collection before real-funds launch.",
    audience: "Operators, auditors, launch leads",
    boundary: "This is an execution runbook and evidence checklist, not proof that the custody ceremony is already complete.",
    docPath: "docs/production-custody-ceremony.md",
    rawHref: `${repositoryBlobBase}/docs/production-custody-ceremony.md`,
  },
  {
    slug: "multisig-setup-intake",
    title: "Multisig Setup Intake",
    category: "Operations",
    summary: "Strict intake shape for the multisig ceremony, signer roster, timelock evidence, and authority transfer proof.",
    audience: "Operators, auditors, launch leads, judges",
    boundary: "This is the input shape and readiness record; it is not itself proof that the production transfer is complete.",
    docPath: "docs/multisig-setup-intake.md",
    rawHref: `${repositoryBlobBase}/docs/multisig-setup-intake.md`,
  },
  {
    slug: "squads-devnet-multisig-ceremony",
    title: "Squads Mainnet Custody Ceremony Reference",
    category: "Operations",
    summary: "Exact operator sequence for the real Squads mainnet custody ceremony, with the Devnet rehearsal clearly separated as an SPL Token 2022 multisig artifact.",
    audience: "Operators, auditors, judges, launch leads",
    boundary: "This is the custody ceremony reference for mainnet closure; it does not claim that the authority transfer has already happened.",
    docPath: "docs/squads-devnet-multisig-ceremony.md",
    rawHref: `${repositoryBlobBase}/docs/squads-devnet-multisig-ceremony.md`,
  },
  {
    slug: "canonical-custody-proof",
    title: "Canonical Custody Proof",
    category: "Operations",
    summary: "Repo-backed custody truth packet with exact ceremony gates, observed chain readouts, and explorer-linked closure points.",
    audience: "Operators, auditors, judges, buyers",
    boundary: "Truth packet only; it does not claim that production multisig or authority transfer signatures already exist.",
    docPath: "docs/canonical-custody-proof.generated.md",
    rawHref: `${repositoryBlobBase}/docs/canonical-custody-proof.generated.md`,
  },
  {
    slug: "custody-proof-reviewer-packet",
    title: "Custody Proof Reviewer Packet",
    category: "Reviewer core",
    summary: "Reviewer-facing custody truth packet that condenses what is externally proven now, what remains ceremony-gated, and the exact strict ingestion route for ceremony evidence.",
    audience: "Judges, auditors, technical reviewers, launch leads",
    boundary: "Reviewer condensation only; it does not claim ceremony completion until the exact external artifacts exist.",
    docPath: "docs/custody-proof-reviewer-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/custody-proof-reviewer-packet.generated.md`,
  },
  {
    slug: "track-judge-first-openings",
    title: "Judge-First Openings",
    category: "Reviewer core",
    summary: "Canonical 30 to 45 second opening copy for the priority product lanes, kept aligned with the judge-first top strip and reviewer packet.",
    audience: "Judges, reviewers, founders, video editors",
    boundary: "Presentation alignment surface only; it does not change what is proven, pending, or externally blocked.",
    docPath: "docs/track-judge-first-openings.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-judge-first-openings.generated.md`,
  },
  {
    slug: "strategic-opportunity-readiness-2026",
    title: "Strategic Opportunity Readiness 2026",
    category: "Strategy",
    summary: "Truth-aligned readiness map for grants, analytics, confidential payout, hardening, and product delivery corridors.",
    audience: "Founders, judges, grant reviewers, operators",
    boundary: "Strategic alignment surface only; it does not claim wins, funding, or integrations that are not already evidenced.",
    docPath: "docs/strategic-opportunity-readiness-2026.md",
    rawHref: `${repositoryBlobBase}/docs/strategic-opportunity-readiness-2026.md`,
  },
  {
    slug: "ecosystem-focus-alignment",
    title: "Ecosystem Focus Alignment",
    category: "Strategy",
    summary: "Generated reviewer-visible mapping from the live product into decentralisation, censorship resistance, DAO tooling, education, developer tooling, payments, and selective cause-driven fit.",
    audience: "Grant reviewers, partners, judges, founders",
    boundary: "Alignment packet only; it does not claim every ecosystem corridor is equally mature or externally validated.",
    docPath: "docs/ecosystem-focus-alignment.generated.md",
    rawHref: `${repositoryBlobBase}/docs/ecosystem-focus-alignment.generated.md`,
  },
  {
    slug: "track-reviewer-packet-colosseum-frontier",
    title: "Core Reviewer Packet",
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("colosseum-frontier"),
    audience: "Judges, reviewers, founders",
    boundary: "Reviewer packet only; it does not alter the underlying trust or gate truth.",
    docPath: "docs/track-reviewer-packets/colosseum-frontier.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/colosseum-frontier.generated.md`,
  },
  {
    slug: "track-reviewer-packet-privacy-track",
    title: "Privacy Reviewer Packet",
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("privacy-track"),
    audience: "Judges, reviewers, founders",
    boundary: "Reviewer packet only; it does not alter the underlying trust or gate truth.",
    docPath: "docs/track-reviewer-packets/privacy-track.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/privacy-track.generated.md`,
  },
  {
    slug: "track-reviewer-packet-rpc-infrastructure",
    title: "Runtime Reviewer Packet",
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("rpc-infrastructure"),
    audience: "Judges, reviewers, founders",
    boundary: "Reviewer packet only; it does not alter the underlying trust or gate truth.",
    docPath: "docs/track-reviewer-packets/rpc-infrastructure.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/rpc-infrastructure.generated.md`,
  },
  {
    slug: "external-audit-engagement",
    title: "External Audit Engagement",
    category: "Operations",
    summary: "Audit intake and boundary packet for external reviewers, including release-gate truth and required evidence surfaces.",
    audience: "Auditors, operators, security reviewers",
    boundary: "Captures audit readiness and requested evidence, not external sign-off itself.",
    docPath: "docs/external-audit-engagement.md",
    rawHref: `${repositoryBlobBase}/docs/external-audit-engagement.md`,
  },
  {
    slug: "authority-hardening-mainnet",
    title: "Authority Hardening for Mainnet",
    category: "Operations",
    summary: "Canonical authority-separation brief covering multisig posture, upgrade authority, treasury authority, and admin-boundary discipline before Mainnet.",
    audience: "Operators, auditors, reviewers, buyers",
    boundary: "Launch-discipline surface only; it does not claim the ceremony is already complete.",
    docPath: "docs/authority-hardening-mainnet.md",
    rawHref: `${repositoryBlobBase}/docs/authority-hardening-mainnet.md`,
  },
  {
    slug: "incident-readiness-runbook",
    title: "Incident Readiness Runbook",
    category: "Operations",
    summary: "Canonical runbook for RPC, wallet, instruction, and proposal-state monitoring with a compact operator response loop.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Runbook surface only; it does not claim 24/7 coverage or external IR membership.",
    docPath: "docs/incident-readiness-runbook.md",
    rawHref: `${repositoryBlobBase}/docs/incident-readiness-runbook.md`,
  },
  {
    slug: "monitoring-alert-rules",
    title: "Monitoring Alert Rules",
    category: "Operations",
    summary: "Machine-checked monitoring and alert rules for RPC, wallet, proposal-state, and hosted-read runtime visibility.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Rules surface only; it does not claim external monitoring closure beyond the underlying evidence boundary.",
    docPath: "docs/monitoring-alert-rules.md",
    rawHref: `${repositoryBlobBase}/docs/monitoring-alert-rules.md`,
  },
  {
    slug: "governance-runtime-proof",
    title: "Governance Runtime Proof Status",
    category: "Operations",
    summary: "Machine-checked packet that separates live wallet-first governance capability from repo proof, browser-wallet proof, and real-device proof capture.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Truth packet only; it does not claim browser-wallet or real-device governance action proof until those captures are recorded.",
    docPath: "docs/governance-runtime-proof.generated.md",
    rawHref: `${repositoryBlobBase}/docs/governance-runtime-proof.generated.md`,
  },
  {
    slug: "real-device-runtime",
    title: "Real-Device Runtime Evidence",
    category: "Operations",
    summary: "Canonical real-device wallet runtime evidence package with capture coverage, active targets, and reviewer-visible Devnet proof.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Runtime evidence surface only; it does not claim all target devices are closed beyond the recorded capture set.",
    docPath: "docs/runtime/real-device.generated.md",
    rawHref: `${repositoryBlobBase}/docs/runtime/real-device.generated.md`,
  },
  {
    slug: "android-solflare-real-device-capture-2026-04-18",
    title: "Android Solflare Real-Device Capture",
    category: "Operations",
    summary: "Samsung Android capture proving PrivateDAO execution from the Solflare mobile wallet browser on Devnet, including DAO creation, proposal creation, commit vote, wallet approvals, and same-device explorer verification.",
    audience: "Operators, reviewers, judges, non-technical buyers",
    boundary: "Real-device packet only; it proves the captured mobile path without claiming the remaining Android reveal, finalize, or execute stages are already closed.",
    docPath: "docs/android-solflare-real-device-capture-2026-04-18.md",
    rawHref: `${repositoryBlobBase}/docs/android-solflare-real-device-capture-2026-04-18.md`,
  },
  {
    slug: "frontier-integrations",
    title: "Integration Evidence",
    category: "Reviewer core",
    summary: "Unified packet for ZK anchors, REFHE envelopes, MagicBlock corridor evidence, and Fast RPC-backed runtime surfaces.",
    audience: "Judges, reviewers, technical operators",
    boundary: "Reviewer-facing integration surface only; source-verifiable external receipts remain a separate launch boundary.",
    docPath: "docs/frontier-integrations.generated.md",
    rawHref: `${repositoryBlobBase}/docs/frontier-integrations.generated.md`,
  },
  {
    slug: "frontier-competition-readiness-2026",
    title: "Product Opportunity Readiness 2026",
    category: "Strategy",
    summary: "Truth-aligned readiness map across the current product opportunity set beyond the core reviewer lane.",
    audience: "Founders, judges, strategy reviewers, operators",
    boundary: "Strategy surface only; it does not claim partner integrations or shipped behaviors beyond what already exists in the repo.",
    docPath: "docs/frontier-competition-readiness-2026.md",
    rawHref: `${repositoryBlobBase}/docs/frontier-competition-readiness-2026.md`,
  },
  {
    slug: "competition-track-requirements-2026",
    title: "Product Alignment 2026",
    category: "Strategy",
    summary: "Public alignment note mapping current product truth to the main technical lenses reviewers care about.",
    audience: "Founders, judges, grant reviewers, operators",
    boundary: "Alignment note only; it describes public product fit and evidence boundaries without exposing private sponsor tactics.",
    docPath: "docs/competition-track-requirements-2026.md",
    rawHref: `${repositoryBlobBase}/docs/competition-track-requirements-2026.md`,
  },
  {
    slug: "telemetry-export-packet",
    title: "Telemetry Export Packet",
    category: "Strategy",
    summary: "Reviewer-safe packet for telemetry and infrastructure corridors showing how runtime evidence, diagnostics, analytics, and hosted reads already map to real product value.",
    audience: "Judges, grant reviewers, infra reviewers, operators",
    boundary: "Telemetry packet only; it does not claim partner-native dashboards or a production mainnet data plane.",
    docPath: "docs/telemetry-export-packet.md",
    rawHref: `${repositoryBlobBase}/docs/telemetry-export-packet.md`,
  },
  {
    slug: "confidential-payout-evidence-packet",
    title: "Confidential Payout Evidence Packet",
    category: "Strategy",
    summary: "Reviewer-visible packet for private payout and treasury motion corridors showing how confidentiality, governance, and trust surfaces already connect on Devnet.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Evidence packet only; it does not claim production-ready real-funds payout or completed external audit and receipt requirements.",
    docPath: "docs/confidential-payout-evidence-packet.md",
    rawHref: `${repositoryBlobBase}/docs/confidential-payout-evidence-packet.md`,
  },
  {
    slug: "capital-readiness-packet",
    title: "Capital Readiness Packet",
    category: "Strategy",
    summary: "Capital-facing packet tying product, services, trust, and release-path truth together for accelerator and grant reviewers.",
    audience: "Grant reviewers, accelerator reviewers, founders, operators",
    boundary: "Capital-readiness packet only; it does not claim that production, custody, audit, or monitoring gates are already complete.",
    docPath: "docs/capital-readiness-packet.md",
    rawHref: `${repositoryBlobBase}/docs/capital-readiness-packet.md`,
  },
  {
    slug: "poland-foundation-grant-application-packet",
    title: "Poland Foundation Grant Application Packet",
    category: "Grants",
    summary: "Application-ready packet for regional and foundation-style grant review, including concise problem framing, proof-of-work routes, milestones, KPIs, and a disciplined release boundary.",
    audience: "Grant reviewers, regional ecosystem reviewers, founders, operators",
    boundary: "Application packet only; it sharpens the current grant posture without claiming completed audit, custody completion, or production real-funds readiness.",
    docPath: "docs/poland-foundation-grant-application-packet.md",
    rawHref: `${repositoryBlobBase}/docs/poland-foundation-grant-application-packet.md`,
  },
  {
    slug: "startup-accelerator-application-packet",
    title: "Startup Accelerator Application Packet",
    category: "Grants",
    summary: "Application-ready packet for accelerator reviewers showing why PrivateDAO already behaves like a serious product with clear capital use and a disciplined path to production readiness.",
    audience: "Accelerator reviewers, grant reviewers, founders, operators",
    boundary: "Application packet only; it does not claim finished audit, custody completion, monitoring completion, or production real-funds readiness.",
    docPath: "docs/startup-accelerator-application-packet.md",
    rawHref: `${repositoryBlobBase}/docs/startup-accelerator-application-packet.md`,
  },
  {
    slug: "funding-readiness-scorecard",
    title: "Funding Readiness Scorecard",
    category: "Grants",
    summary: "Fast scorecard for funders showing what is shipped now, what capital directly unlocks, and which remaining gates still matter before production release.",
    audience: "Grant reviewers, accelerator reviewers, operators, founders",
    boundary: "Readiness scorecard only; it clarifies the current posture without overstating gate completion or production readiness.",
    docPath: "docs/funding-readiness-scorecard.md",
    rawHref: `${repositoryBlobBase}/docs/funding-readiness-scorecard.md`,
  },
  {
    slug: "runtime-operations-readiness-packet",
    title: "Runtime Operations Readiness Packet",
    category: "Operations",
    summary: "Single packet for funders and reviewers showing the current real-device wallet matrix lift, monitoring delivery lift, and why these are the highest-value operational unlocks before production claims.",
    audience: "Grant reviewers, accelerator reviewers, operators, founders",
    boundary: "Operations packet only; it clarifies the current runtime and monitoring posture without claiming those operating lifts are already complete.",
    docPath: "docs/runtime-operations-readiness-packet.md",
    rawHref: `${repositoryBlobBase}/docs/runtime-operations-readiness-packet.md`,
  },
  {
    slug: "execution-unlock-bundle",
    title: "Execution Unlock Bundle",
    category: "Operations",
    summary: "Generated bundle that compresses the three highest-value remaining closures: real-device wallet coverage, monitoring delivery, and settlement receipt closure.",
    audience: "Funders, judges, operators, reviewers",
    boundary: "Generated bundle only; it summarizes release posture without claiming those gates are already complete.",
    docPath: "docs/execution-unlock-bundle.generated.md",
    rawHref: `${repositoryBlobBase}/docs/execution-unlock-bundle.generated.md`,
  },
  {
    slug: "real-device-capture-closure-packet",
    title: "Real-Device Capture Closure Packet",
    category: "Trust",
    summary: "Execution packet for advancing the remaining wallet matrix lift with target-by-target capture standards, evidence requirements, and reviewer-visible boundaries.",
    audience: "Funders, judges, operators, reviewers",
    boundary: "Closure program only; it does not claim the wallet matrix is already complete or that browser-only proof replaces real-device capture.",
    docPath: "docs/real-device-capture-closure-packet.md",
    rawHref: `${repositoryBlobBase}/docs/real-device-capture-closure-packet.md`,
  },
  {
    slug: "runtime-evidence",
    title: "Runtime Evidence",
    category: "Runtime",
    summary:
      "Generated runtime package consolidating runtime attestation, wallet compatibility, Devnet canary, resilience evidence, MagicBlock runtime notes, and ZK-enforced runtime references.",
    audience: "Judges, reviewers, operators, infrastructure partners",
    boundary:
      "Generated evidence package only; it reports the captured runtime posture and linked verification commands without upgrading unclosed production or mainnet gates.",
    docPath: "docs/runtime-evidence.generated.md",
    rawHref: `${repositoryBlobBase}/docs/runtime-evidence.generated.md`,
  },
  {
    slug: "authority-transfer-runbook",
    title: "Authority Transfer Runbook",
    category: "Custody",
    summary:
      "Operational runbook for authority transfer, multisig custody, timelock posture, backup procedures, and incident-facing governance controls.",
    audience: "Operators, custody reviewers, security reviewers, launch partners",
    boundary:
      "Runbook only; it documents the required custody process and evidence dependencies without claiming a production authority transfer has been executed.",
    docPath: "docs/authority-transfer-runbook.md",
    rawHref: `${repositoryBlobBase}/docs/authority-transfer-runbook.md`,
  },
  {
    slug: "grant-committee-pack",
    title: "Grant Committee Pack",
    category: "Grants",
    summary:
      "Compact grant-review packet linking the product routes, use-case proof, service surface, and committee-facing evidence needed for funding review.",
    audience: "Grant committees, ecosystem reviewers, operators, partners",
    boundary:
      "Grant packet only; it organizes available proof and product routes without claiming funding approval or unverified production deployments.",
    docPath: "docs/grant-committee-pack.md",
    rawHref: `${repositoryBlobBase}/docs/grant-committee-pack.md`,
  },
  {
    slug: "settlement-receipt-closure-packet",
    title: "Settlement Receipt Closure Packet",
    category: "Trust",
    summary: "Execution packet for the remaining privacy-settlement evidence target: what is already true on Devnet, what still matters before production payout claims, and what evidence closes the gap.",
    audience: "Funders, judges, buyers, operators",
    boundary: "Closure packet only; it does not claim source-verifiable settlement receipts are already closed or that confidential payout is already mainnet real-funds ready.",
    docPath: "docs/settlement-receipt-closure-packet.md",
    rawHref: `${repositoryBlobBase}/docs/settlement-receipt-closure-packet.md`,
  },
  {
    slug: "settlement-receipt-closure",
    title: "Settlement Receipt Closure",
    category: "Trust",
    summary:
      "Generated closure evidence for settlement receipt requirements, linked supporting artifacts, and the remaining boundary before stronger production payout claims.",
    audience: "Funders, judges, buyers, operators, reviewers",
    boundary:
      "Generated closure evidence only; it does not claim source-verifiable settlement receipts are already closed.",
    docPath: "docs/settlement-receipt-closure.generated.md",
    rawHref: `${repositoryBlobBase}/docs/settlement-receipt-closure.generated.md`,
  },
  {
    slug: "mainnet-execution-readiness-packet",
    title: "Mainnet Execution Readiness Packet",
    category: "Launch",
    summary:
      "Mainnet execution readiness packet covering execution gates, launch dependencies, monitoring posture, custody requirements, and reviewer-visible proof routes.",
    audience: "Launch reviewers, operators, security reviewers, infrastructure partners",
    boundary:
      "Readiness packet only; it describes mainnet preparation and remaining gates without claiming mainnet production release is complete.",
    docPath: "docs/mainnet-execution-readiness-packet.md",
    rawHref: `${repositoryBlobBase}/docs/mainnet-execution-readiness-packet.md`,
  },
  {
    slug: "launch-ops-checklist",
    title: "Launch Ops Checklist",
    category: "Launch",
    summary:
      "Human-readable launch operations checklist mapping mainnet blockers to custody, monitoring, wallet runtime, MagicBlock, REFHE, and cutover evidence.",
    audience: "Operators, launch reviewers, security reviewers, ecosystem partners",
    boundary:
      "Checklist only; it tracks required launch controls and evidence paths without claiming all checklist items are closed.",
    docPath: "docs/launch-ops-checklist.md",
    rawHref: `${repositoryBlobBase}/docs/launch-ops-checklist.md`,
  },
  {
    slug: "monitoring-delivery-closure-packet",
    title: "Monitoring Delivery Closure Packet",
    category: "Trust",
    summary: "Execution packet for closing live alert routing, operator ownership, and tested transcript gaps between the in-repo rulebook and believable production monitoring delivery.",
    audience: "Funders, judges, operators, reviewers",
    boundary: "Closure packet only; it does not claim live alert routing, tested transcripts, or exercised production incident ownership already exist.",
    docPath: "docs/monitoring-delivery-closure-packet.md",
    rawHref: `${repositoryBlobBase}/docs/monitoring-delivery-closure-packet.md`,
  },
  {
    slug: "monitoring-delivery-evidence",
    title: "Monitoring Delivery Evidence",
    category: "Operations",
    summary: "Generated evidence package for monitoring delivery ownership, requirement closure, transcript expectations, and current claim boundary.",
    audience: "Funders, judges, operators, reviewers",
    boundary: "Generated evidence only; it does not claim live alert routing or tested production transcripts are already complete.",
    docPath: "docs/monitoring-delivery.generated.md",
    rawHref: `${repositoryBlobBase}/docs/monitoring-delivery.generated.md`,
  },
  {
    slug: "monitoring-delivery-evidence-packet",
    title: "Monitoring Delivery Evidence Packet",
    category: "Operations",
    summary: "Explains what is already defined for monitoring and alerts, what still requires delivery completion, and why this is one of the clearest execution unlocks before stronger production claims.",
    audience: "Grant reviewers, accelerator reviewers, operators, founders",
    boundary: "Operations packet only; it does not claim live alert routing or production incident ownership is already closed.",
    docPath: "docs/monitoring-delivery-evidence-packet.md",
    rawHref: `${repositoryBlobBase}/docs/monitoring-delivery-evidence-packet.md`,
  },
  {
    slug: "settlement-receipt-closure-evidence",
    title: "Settlement Receipt Closure Evidence",
    category: "Trust",
    summary: "Generated evidence package for the privacy-settlement closure program, including requirement counts and linked supporting artifacts.",
    audience: "Funders, judges, buyers, reviewers",
    boundary: "Generated closure evidence only; it does not claim source-verifiable settlement receipts are already closed.",
    docPath: "docs/settlement-receipt-closure.generated.md",
    rawHref: `${repositoryBlobBase}/docs/settlement-receipt-closure.generated.md`,
  },
  {
    slug: "competition-execution-playbook",
    title: "Product Execution Playbook",
    category: "Strategy",
    summary: "Development playbook for keeping product, docs, proof, and UX aligned with the current operating targets.",
    audience: "Founders, operators, product leads, reviewers",
    boundary: "Execution guidance only; it does not by itself upgrade the repo beyond what is actually implemented.",
    docPath: "docs/competition-execution-playbook.md",
    rawHref: `${repositoryBlobBase}/docs/competition-execution-playbook.md`,
  },
  {
    slug: "ecosystem-operating-brief-2026",
    title: "2026 Operating Brief",
    category: "Strategy",
    summary: "Operating interpretation of the current ecosystem, security, and infrastructure signals shaping PrivateDAO.",
    audience: "Founders, operators, judges, security reviewers",
    boundary: "Operating brief only; it does not replace the underlying proof, launch, or runtime evidence surfaces.",
    docPath: "docs/colosseum-frontier-2026-operating-brief.md",
    rawHref: `${repositoryBlobBase}/docs/colosseum-frontier-2026-operating-brief.md`,
  },
  {
    slug: "product-overview-video",
    title: "Product Overview Video Package",
    category: "Strategy",
    summary: "Canonical brief for the comprehensive product reel that explains everything PrivateDAO offers and why it is positioned to serve the ecosystem well.",
    audience: "Judges, buyers, operators, content reviewers",
    boundary: "Video brief and asset package only; it does not change the underlying proof or launch boundary documents.",
    docPath: "docs/investor-video.md",
    rawHref: `${repositoryBlobBase}/docs/investor-video.md`,
  },
];

export function getCuratedDocuments() {
  return curatedDocuments.filter((entry) => isPublicCuratedDocumentSlug(entry.slug));
}

export function getCuratedDocumentsBySlugs(slugs: string[]) {
  const documentMap = new Map(getCuratedDocuments().map((entry) => [entry.slug, entry]));
  return slugs
    .map((slug) => documentMap.get(slug))
    .filter((entry): entry is CuratedDocument => entry !== undefined);
}

export function getCuratedDocument(slug: string) {
  if (!isPublicCuratedDocumentSlug(slug)) return null;
  return curatedDocuments.find((entry) => entry.slug === slug) ?? null;
}

export function getCuratedDocumentContent(slug: string) {
  const entry = getCuratedDocument(slug);
  if (!entry) return null;

  const docsRoot = path.join(/* turbopackIgnore: true */ process.cwd(), "..", "..", "docs");
  const relativeDocPath = entry.docPath.replace(/^docs\//, "");
  const absolutePath = path.join(docsRoot, relativeDocPath);
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Missing curated document source: ${entry.docPath}`);
  }

  return {
    ...entry,
    content: fs.readFileSync(absolutePath, "utf8"),
  };
}
