import { supportedLocales } from "@/lib/i18n";

export const siteName = "PrivateDAO";
export const siteTitle = "PrivateDAO | Private Governance, Payroll, and Treasury on Solana";
export const siteDescription =
  "Your DAO votes, payroll, and treasury are public. They shouldn't be. PrivateDAO bridges organizational privacy and onchain verifiability with confidential governance, encrypted treasury coordination, and Solana-native operational infrastructure.";
export const siteUrl = process.env.NEXT_PUBLIC_LIVE_SITE_URL?.replace(/\/+$/, "") ?? "https://privatedao.org";
export const defaultOgImage = `${siteUrl}/opengraph-image.png`;

export const siteKeywords = [
  "PrivateDAO",
  "Private DAO",
  "PrivateDAO workflow",
  "PrivateDAO Stack",
  "PrivateDAO Solana Testnet",
  "PrivateDAO private rooms",
  "PrivateDAO public DAO",
  "confidential governance",
  "encrypted treasury coordination",
  "organizational infrastructure",
  "post-governance operating system",
  "private coordination layer",
  "public verification",
  "transparency report",
  "asset context",
  "token risk context",
  "price context",
  "confidential vesting",
  "private governance",
  "private DAO governance",
  "private room DAO",
  "public DAO private voting",
  "confidential treasury",
  "confidential treasury request",
  "treasury policy",
  "encrypted payments",
  "confidential payroll",
  "encrypted payroll",
  "private payroll",
  "GamingDAO",
  "gaming DAO rewards",
  "Android Solana app",
  "sovereign intelligence",
  "decision intelligence",
  "AI decision support",
  "wallet-first execution",
  "Solana Testnet app",
  "Solana Testnet governance",
  "Solana Testnet voting",
  "Solana wallet connect",
  "Solana wallet QR",
  "Solana private room",
  "Solana Android app",
  "Solana encrypted payments",
  "Solana confidential payroll",
  "Solana private governance",
  "private voting",
  "Solana governance",
  "Solana treasury",
  "Solana DAO infrastructure",
  "DAO treasury infrastructure",
  "Solana operational infrastructure",
  "Solana production readiness",
  "Solana Testnet readiness",
  "Solana RPC services",
  "Solana read node",
  "QuickNode Streams",
  "QuickNode Solana Testnet",
  "readiness aggregate",
  "backend telemetry",
  "runtime telemetry",
  "proof freshness",
  "API health",
  "AWS read node",
  "Supabase receipts",
  "Covalent data intelligence",
  "on-chain verification",
  "ZK verifier",
  "Squads multisig",
  "timelock enforcement",
  "Token-2022",
  "Anchor 1",
  "QVAC",
  "MagicBlock",
  "GoldRush",
  "Covalent GoldRush",
  "IKA",
  "Umbra",
  "Cloak",
  "Torque",
  "Solana Mobile",
  "REFHE",
  "ZK",
  "Hosted reads",
  "حوكمة خاصة",
  "تصويت خاص",
  "خزينة مشفرة",
  "رواتب مشفرة",
  "برايفيت داو",
  "داو خاص على سولانا",
  "частное управление DAO",
  "конфиденциальное голосование",
  "приватне голосування DAO",
  "gobernanza privada DAO",
  "tesoreria confidencial DAO",
  "governance privata DAO",
  "confidential DAO payroll",
];

export function buildOrganizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: siteName,
    alternateName: ["Private DAO"],
    url: siteUrl,
    logo: `${siteUrl}/assets/logo.png`,
    sameAs: [
      "https://github.com/X-PACT/PrivateDAO",
      "https://www.youtube.com/@privatedao",
      "https://discord.gg/GjJykUtTTt",
      "https://arena.colosseum.org/projects/explore/praivatedao",
      "https://superteam.fun/earn/t/Private-dao-1",
      "https://x.com/privateDAOOS",
      "https://t.me/Fahdkotb",
    ],
  };
}

export function buildWebSiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteName,
    alternateName: ["Private DAO"],
    url: siteUrl,
    inLanguage: supportedLocales.map((locale) => locale.code),
    keywords: siteKeywords,
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteUrl}/search/?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
}

export function buildSoftwareApplicationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: siteName,
    alternateName: ["Private DAO", "PrivateDAO Solana"],
    url: siteUrl,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web, Android",
    description: siteDescription,
    keywords: siteKeywords.join(", "),
    softwareHelp: `${siteUrl}/learn/`,
    downloadUrl: `${siteUrl}/android/`,
    featureList: [
      "Solana Testnet wallet-first governance",
      "Private commit-reveal voting posture",
      "Confidential payroll and encrypted payments",
      "Treasury policy review and execution",
      "GamingDAO rewards and tournaments",
      "Local-first decision intelligence",
      "QuickNode-backed Solana Testnet telemetry",
      "Reviewer-safe readiness aggregate API",
      "Hosted read-node health and metrics",
      "Supabase-backed operation receipt posture",
      "Reviewer-visible proof and runtime evidence",
      "Standalone Testnet ZK verifier receipt",
      "Squads multisig timelock enforcement proof",
      "PDAO Token-2022 fixed-supply governance mint",
    ],
    sameAs: [
      "https://github.com/X-PACT/PrivateDAO",
      "https://x.com/privateDAOOS",
      "https://www.youtube.com/@privatedao",
      "https://discord.gg/GjJykUtTTt",
      "https://arena.colosseum.org/projects/explore/praivatedao",
      "https://superteam.fun/earn/t/Private-dao-1",
      "https://t.me/Fahdkotb",
    ],
  };
}
